server:
    port: 8089
spring:
  application:
    name: order-sentinel
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8801
      web-context-unify: false   #默认将调用链路收敛了

#从nacos中读取流控规则
#      datasource:
#        flow-rules:
#          nacos:
#            server-addr: localhost:8848
#            data-id: flow-rules
#            group-id: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow



