server:
  port: 8083

spring:
  application:
    name: spring-boot-admin-server
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
management:
  endpoints:
    web:
      exposure:
        include: '*'